add_subdirectory(actionids)
add_subdirectory(cpudetect)
add_subdirectory(gamedirs)
add_subdirectory(ini)
add_subdirectory(logstress)
add_subdirectory(netpacket)
add_subdirectory(socketudp)
add_subdirectory(sosparity)
add_subdirectory(spawner)
add_subdirectory(spawnhouse)
add_subdirectory(syncrec)
add_subdirectory(unvqdelta)
add_subdirectory(colorops)
add_subdirectory(voxeldraw)
add_subdirectory(unvqdec)
add_subdirectory(lcwcomp)
add_subdirectory(lcwblock)
add_subdirectory(autosave)
add_subdirectory(audioring)
add_subdirectory(audiohandle)
add_subdirectory(audiolevel)
add_subdirectory(auddecode)
add_subdirectory(audiocache)
add_subdirectory(audiomixer)
add_subdirectory(audiostream)
add_subdirectory(audioevent)
add_subdirectory(soundini)
add_subdirectory(voxqueue)
add_subdirectory(desync)
add_subdirectory(scenfile)
add_subdirectory(deploymentconfig)
add_subdirectory(tutorial)
add_subdirectory(utf8)
add_subdirectory(shapefacing)
add_subdirectory(save)
