#pragma once
#include <windows.h>

// The control wrappers Windows spells as macros over SendMessage. Keeping them as macros
// keeps the call sites identical to the supported build.
#define Button_GetCheck(hwnd) ((int)SendMessage((hwnd), BM_GETCHECK, 0, 0))
#define Button_SetCheck(hwnd, check) ((void)SendMessage((hwnd), BM_SETCHECK, (WPARAM)(int)(check), 0))
#define Button_Enable(hwnd, enable) EnableWindow((hwnd), (BOOL)(enable))
#define Button_SetText(hwnd, text) SetWindowText((hwnd), (text))
#define Static_SetText(hwnd, text) SetWindowText((hwnd), (text))
#define Edit_SetText(hwnd, text) SetWindowText((hwnd), (text))
#define Edit_GetText(hwnd, text, max) GetWindowText((hwnd), (text), (max))

#define ListBox_AddString(hwnd, text) ((int)SendMessage((hwnd), LB_ADDSTRING, 0, (LPARAM)(LPCSTR)(text)))
#define ListBox_InsertString(hwnd, index, text) ((int)SendMessage((hwnd), LB_INSERTSTRING, (WPARAM)(int)(index), (LPARAM)(LPCSTR)(text)))
#define ListBox_DeleteString(hwnd, index) ((int)SendMessage((hwnd), LB_DELETESTRING, (WPARAM)(int)(index), 0))
#define ListBox_ResetContent(hwnd) ((BOOL)SendMessage((hwnd), LB_RESETCONTENT, 0, 0))
#define ListBox_GetCount(hwnd) ((int)SendMessage((hwnd), LB_GETCOUNT, 0, 0))
#define ListBox_GetCurSel(hwnd) ((int)SendMessage((hwnd), LB_GETCURSEL, 0, 0))
#define ListBox_SetCurSel(hwnd, index) ((int)SendMessage((hwnd), LB_SETCURSEL, (WPARAM)(int)(index), 0))
#define ListBox_GetSel(hwnd, index) ((int)SendMessage((hwnd), LB_GETSEL, (WPARAM)(int)(index), 0))
#define ListBox_SetSel(hwnd, select, index) ((int)SendMessage((hwnd), LB_SETSEL, (WPARAM)(BOOL)(select), (LPARAM)(int)(index)))
#define ListBox_GetText(hwnd, index, text) ((int)SendMessage((hwnd), LB_GETTEXT, (WPARAM)(int)(index), (LPARAM)(LPCSTR)(text)))
#define ListBox_GetItemData(hwnd, index) ((LRESULT)SendMessage((hwnd), LB_GETITEMDATA, (WPARAM)(int)(index), 0))
#define ListBox_SetItemData(hwnd, index, data) ((int)SendMessage((hwnd), LB_SETITEMDATA, (WPARAM)(int)(index), (LPARAM)(data)))
#define ListBox_SetTopIndex(hwnd, index) ((int)SendMessage((hwnd), LB_SETTOPINDEX, (WPARAM)(int)(index), 0))
#define ListBox_GetTopIndex(hwnd) ((int)SendMessage((hwnd), LB_GETTOPINDEX, 0, 0))
#define ListBox_FindStringExact(hwnd, start, text) ((int)SendMessage((hwnd), LB_FINDSTRINGEXACT, (WPARAM)(int)(start), (LPARAM)(LPCSTR)(text)))
#define ListBox_SetItemHeight(hwnd, index, height) ((int)SendMessage((hwnd), LB_SETITEMHEIGHT, (WPARAM)(int)(index), MAKELPARAM((height), 0)))
#define ListBox_GetItemHeight(hwnd, index) ((int)SendMessage((hwnd), LB_GETITEMHEIGHT, (WPARAM)(int)(index), 0))

#define ComboBox_AddString(hwnd, text) ((int)SendMessage((hwnd), CB_ADDSTRING, 0, (LPARAM)(LPCSTR)(text)))
#define ComboBox_InsertString(hwnd, index, text) ((int)SendMessage((hwnd), CB_INSERTSTRING, (WPARAM)(int)(index), (LPARAM)(LPCSTR)(text)))
#define ComboBox_DeleteString(hwnd, index) ((int)SendMessage((hwnd), CB_DELETESTRING, (WPARAM)(int)(index), 0))
#define ComboBox_ResetContent(hwnd) ((int)SendMessage((hwnd), CB_RESETCONTENT, 0, 0))
#define ComboBox_GetCount(hwnd) ((int)SendMessage((hwnd), CB_GETCOUNT, 0, 0))
#define ComboBox_GetCurSel(hwnd) ((int)SendMessage((hwnd), CB_GETCURSEL, 0, 0))
#define ComboBox_SetCurSel(hwnd, index) ((int)SendMessage((hwnd), CB_SETCURSEL, (WPARAM)(int)(index), 0))
#define ComboBox_FindString(hwnd, start, text) ((int)SendMessage((hwnd), CB_FINDSTRING, (WPARAM)(int)(start), (LPARAM)(LPCSTR)(text)))
#define ComboBox_GetItemData(hwnd, index) ((LRESULT)SendMessage((hwnd), CB_GETITEMDATA, (WPARAM)(int)(index), 0))
#define ComboBox_SetItemData(hwnd, index, data) ((int)SendMessage((hwnd), CB_SETITEMDATA, (WPARAM)(int)(index), (LPARAM)(data)))
#define ComboBox_GetLBText(hwnd, index, text) ((int)SendMessage((hwnd), CB_GETLBTEXT, (WPARAM)(int)(index), (LPARAM)(LPCSTR)(text)))
#define ComboBox_GetDroppedControlRect(hwnd, rect) ((void)SendMessage((hwnd), CB_GETDROPPEDCONTROLRECT, 0, (LPARAM)(RECT *)(rect)))
#define ComboBox_GetDroppedState(hwnd) ((BOOL)SendMessage((hwnd), CB_GETDROPPEDSTATE, 0, 0))
#define ComboBox_ShowDropdown(hwnd, show) ((BOOL)SendMessage((hwnd), CB_SHOWDROPDOWN, (WPARAM)(BOOL)(show), 0))
#define Edit_SetSel(hwnd, start, end) ((void)SendMessage((hwnd), EM_SETSEL, (WPARAM)(int)(start), (LPARAM)(int)(end)))
